import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {openApp,selectFixtureVideo,seekVideo,measureFirstCycle} from '../helpers/app.mjs';
test('saved schema1 has real boundaries, no video, safe edited filename and literal labels',async ({page})=>{
 await openApp(page); await selectFixtureVideo(page); await measureFirstCycle(page);
 const name='<img src=x onerror=alert(1)>';
 await page.locator('#phaseList .phase-name').first().fill(name); await page.locator('#phaseList .phase-name').first().press('Tab');
 await expect(page.locator('#phaseList img')).toHaveCount(0);
 await page.locator('#outputFilename').fill('../CON');
 const pending=page.waitForEvent('download'); await page.locator('#saveAnalysisButton').click(); const download=await pending;
 expect(download.suggestedFilename()).toBe('-CON.tsd.json');
 const text=await readFile(await download.path(),'utf8'), saved=JSON.parse(text);
 expect(saved.schemaVersion).toBe(1);expect(saved.appVersion).toBe('0.3.0');expect(saved.phases[0].label).toBe(name);
 expect(saved.cycles[0].boundaries.map(b=>b.timeUs)).toEqual([0,600000,1800000,2800000,3400000]);
 expect(text).not.toMatch(/blob:|"video"|"undo"|"currentTime"/);
 await expect(page.locator('#saveStatus')).toContainText('ダウンロードを開始しました');
});
test('unfinished save preserves cursor; failed or cancelled replacement preserves analysis',async ({page})=>{
 await openApp(page); await selectFixtureVideo(page); await page.locator('#startCycleButton').click();
 await seekVideo(page,1); await page.locator('#markBoundaryButton').click(); await seekVideo(page,2);
 const pending=page.waitForEvent('download'); await page.locator('#saveAnalysisButton').click(); const download=await pending;
 const saved=JSON.parse(await readFile(await download.path(),'utf8'));
 expect(saved.cycles[0].spans).toHaveLength(1);expect(saved.cycles[0].cursor).not.toBeNull();expect(saved.cycles[0].status).toBe('open');
 await page.locator('#videoInput').setInputFiles({name:'broken.mp4',mimeType:'video/mp4',buffer:Buffer.from([0,1])});
 await expect(page.locator('#errorMessage')).toBeVisible();await expect(page.locator('#phaseList .phase-row')).toHaveCount(2);
 await selectFixtureVideo(page,'portrait.mp4'); await page.locator('#appConfirmCancel').click();
 await expect(page.locator('#phaseList .phase-row')).toHaveCount(2);await expect(page.locator('#undoButton')).toBeEnabled();
 await selectFixtureVideo(page,'portrait.mp4'); await page.locator('#appConfirmOk').click();
 await expect(page.locator('#phaseList .phase-row')).toHaveCount(0);await expect(page.locator('#undoButton')).toBeDisabled();
});
